---
title: "Turismo en las Provincias"
description: |
  Este sitio tiene como objetivo brindar un resumen sistemático de los principales indicadores relativos al turismo en las provincias de Argentina. 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

<style>
p {
font-size: 1rem;
} 

.d-title > p {
font-size: 1rem;
}
</style>

El _**Monitor de Turismo en las Provincias**_ que acá presentamos procura servir como herramienta de consulta de los últimos datos disponibles de una variedad de indicadores relativos al turismo en la Argentina, poniendo el foco en el nivel provincial. 

#### INDICADORES

Los **Indicadores por provincia** incluyen la siguiente información: 

* [**Turismo Interno**](interno.html): Una caracterización del Turismo Interno a partir de la _Encuesta de Viajes y Turismo de los Hogares_ (EVyTH). 

* [**Turismo Receptivo**](receptivo.html): Estimaciones del turismo receptivo a nivel provincial, detallando el flujo de turistas no residentes que salieron por cada paso fronterizo. 

* [**Padrón de Alojamientos**](padron.html): Indicadores relevantes de la oferta hotelera y parahotelera proveniente del _Padrón Único Nacional de Alojamientos_ (PUNA).

* [**Áreas Naturales**](parques.html): Registro de visitaciones a áreas naturales protegidas de carácter nacional a partir de información de la _Administración de Parques Nacionales_ (APN).

* [**Conectividad Aérea**](aereo.html): Datos provenientes de los registros administrativos de la _Autoridad Nacional de Aviación Civil_ (ANAC).

* [**Empresas Turísticas**](empresas.html): Estadísticas de empresas de las _Ramas Características del Turismo_ (RCT) a partir de datos de la _Administración Federal de Ingresos Públicos_ (AFIP).
